apiVersion: v1
kind: Namespace
metadata:
  name: cluster01
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: cluster01
  namespace: cluster01
spec:
    clusterNetwork:
        services:
            cidrBlocks: ["10.254.0.0/16"]
        pods: 
            cidrBlocks: ["10.1.0.0/16"]
        serviceDomain: "cluster.local"
    providerConfig:
      value:
        apiVersion: "lkeproviderconfig/v1alpha1"
        kind: "LkeClusterProviderConfig"
        authorizedKeys:
          - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCagK9ZjexjQrxmCvQpPm4Da7qM9tQ/ldqAHqbORTqkZbAMMm8ASkBYFP8de4+y+K/BxV2iNDo/A/0Jkaw7uJSrH645vWzCbeX2S+hQMaQp2C7HE4aua8pwjL5d1q/YnU/tiznq2Lf74BTp4/mrl4pcmOTZdlUOa/tTN0ZZlZas0+KW9dr9cn4X78HT6n7vN0TOuQQMWTsw1aFxgdNMUDf6as7Z+RzILdG5J7G7QjFBbRzcj/yaRZGpmpaPvP+KV9J+8KsnjvoMNJuvBYQapWqZqv1yUqN45J2UQ9vvJ7H/p2u8+lYvGZ0wVbRB7PTHnsR8bOSW1f0BPoMDWkW+9ZCN asauber@MacBook-Pro-4.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: linode-api-token
  namespace: cluster01
type: Opaque
data:
  token: MTQ2OGI4NmJhZDgwNDFlNDI5YzNlMjAzYzQ1ZGQ4YWQ5MmQxZWQ0Y2Q2NDg0YTZhN2IwMGMxOWQxODBkMTU3MA==
