kind: Service
apiVersion: v1
metadata:
  name: kube-apiserver
  namespace: kube-system-{{ .Release.Namespace }}
  labels:
    run: kube-apiserver
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-protocol: "tcp"
spec:
  type: LoadBalancer
  selector:
    app: kube-apiserver
  ports:
    - name: https
      protocol: TCP
      port: 6443
      targetPort: 6443
