apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccm-linode
  labels:
    app: ccm-linode
  namespace: kube-system-{{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccm-linode
  template:
    metadata:
      labels:
        app: ccm-linode
    spec:
      tolerations:
        # The CCM is a "critical addon"
        - key: "CriticalAddonsOnly"
          operator: "Exists"
        # This taint is set on all Nodes when an external CCM is used
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoSchedule
      hostNetwork: false
      containers:
        - image: linode/linode-cloud-controller-manager:v0.2.3
          imagePullPolicy: Always
          name: ccm-linode
          args:
          - --cloud-provider=linode
          - --v=3
          - --kubeconfig=/etc/kubernetes/admin.conf
          volumeMounts:
          - mountPath: /etc/kubernetes
            name: k8s-admin
          # FOR DEV ONLY, TODO: use a kustomize patch
          - mountPath: /tls
            name: cacert
          #end FOR DEV ONLY
          env:
            - name: LINODE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: linode
                  key: token
            - name: LINODE_REGION
              valueFrom:
                secretKeyRef:
                  name: linode
                  key: region
            # FOR DEV ONLY, TODO: use a kustomize patch
            - name: LINODE_URL
              value: https://api.dev.linode.com/v4/
            - name: LINODE_CA
              value: /tls/cacert.pem
            - name: LINODE_DEBUG
              value: "1"
            #end FOR DEV ONLY
      volumes:
      - name: k8s-admin
        secret:
          secretName: admin-kubeconfig
      # FOR DEV ONLY, TODO: use a kustomize patch
      - secret:
          defaultMode: 420
          secretName: linode-ca
        name: cacert
      #end FOR DEV ONLY